[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
edition = "2018"
name = "aux5"
version = "0.1.0"

[dependencies]
cortex-m = "0.6.0"
panic-halt = "0.2.0"
cortex-m-rt = "0.6.10"
stm32f407g-disc = "0.4.0"